### ISSUE TITLE
Create proposal for near/world mesh

### ISSUE THREAD

**Issue by cabanier** [immersive-web/real-world-geometry#12]
@TrevorFSmith Is it possible for me to create a proposal in the repo that captures the proposed IDL for meshing?
It's by no means finished but having it buried in an issue makes it hard to discuss.

Thanks!

**Comment by TrevorFSmith** [comment]
You should coordinate with the feature lead, John Pallett, but in general it's fine to use a PR to work on proposed IDL if it will function better than an Issue.
