### ISSUE TITLE
Plane detection should be enabled during session creating

### ISSUE THREAD

**Issue by cabanier** [immersive-web/real-world-geometry#14]
From the proposal:
```
xrSession.updateWorldTrackingState({
 planeDetectionState : {
   enabled : true
 }
});
```

This means that the session was already created and the permission dialog already happened.
I think plain detection should be requested during session creation so the user can be prompted for permission.

**Comment by bialpio** [comment]
The way I understand specifying the required / optional features at session creation is that they are meant to signal to the UA that the app might request a feature in the future (ex: in order for the app to request “local-floor” reference space from session, the session has to be requested with “local-floor” required feature). Adding a feature to the `requestSession()` required / optional features does not mean that that the feature will be configured as soon as the session gets created. I wanted to explicitly avoid considering permission prompts in the explainer - the above snippet is meant to configure plane detection on a session with the assumption that the app created the session in a way that allows the use of plane detection feature. Am I missing something in how the `XRSessionInit` dictionary is meant to be used?

**Comment by rcabanier** [comment]
> Am I missing something in how the XRSessionInit dictionary is meant to be used?

@bialpio No. 
All I meant to say is that in order to use the plane detection feature, it needs to be requested during session creation which will likely result in a prompt asking the user for permission.
Where/when _exactly_ the feature is configure or initialized is up to the UA.

**Comment by bialpio** [comment]
Closing stale issue. I'll rework the explainer to align with the other APIs that we've been shipping.
