### ISSUE TITLE
Need a function to get all existing persisted anchor handles

### ISSUE THREAD

**Issue by richardanaya** [immersive-web/real-world-geometry#37]
Right now there's not a way to recall persisted anchors from previous sessions.  As an alternative I turn to using localStorage to store uuids of persisted anchor uuids.  However, sometimes accidents happen and I lose that local storage list and I have a persisted list of anchors in my browser that I cannot access. It would be awesome if there was some function `getPersistentAnchorHandles` that would return me all stored persisted anchor's handles.  A side benefit of this would be to allow me to not have to use localStorage solutions for basic storage of anchors and make my AR application simpler.

**Comment by cabanier** [comment]
We could add a `readonly attribute [FrozenArray](https://webidl.spec.whatwg.org/#idl-frozen-array)<[DOMString](https://webidl.spec.whatwg.org/#idl-DOMString)>persistentAnchors;` to the `XRFrame`.
What do you think?

**Comment by richardanaya** [comment]
That would work too :) probably more consistent that way.

**Comment by cabanier** [comment]
Great! It will be in the next browser release
